on:
  workflow_dispatch:
  push:
    branches: main

name: Update on RPi 4

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH in Pi, PM2 stop, git pull, build, PM2 start
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PI_HOST }}
          username: ${{ secrets.PI_USERNAME }}
          password: "${{ secrets.PI_PASSWORD }}"
          script: |
            cd /var/www/html/kinko
            pm2 stop kinko
            git pull
            cd frontend
            npm run build
            pm2 start kinko
            
            
